### PR TITLE
Add function changeFavicon

### PR DESCRIPTION
**Pull request by avdg**
Usage: changeFavicon('/images/imageYouWant.png');

### CODE REVIEW

**Comment by avdg** [comment]
(hmm... knockout.js is a very new concept for me, but I guess I should attempt to use that first before pushing this solution forwards - give me some time to learn it)

**Comment by ddevault** [comment]
I'll give you time to think about a different solution, but this one is acceptable.

**Comment by avdg** [comment]
Hmm... somehow I can't get this working... not sure what's wrong with it...

This change should work with the current trunk code

```
<link rel="shortcut icon" data-bind="attr: {href: icon()}">
```

We want this - this works in the browser:

```
<link rel="shortcut icon" optional-data-bind-stuff href="/images/blah.png">
```

I really hope there is a stupid mistake, else I guess I'll go for this solution.

~~Edit: I think it doesn't work because the browser only updates the favicon if the whole link tag got removed. So knockout.js is knocked out I'm afraid. I propose to stick to the given solution.~~

Edit: I've tested this in chrome 32.0.1700.107 m

Edit: found a solution

**Comment by avdg** [comment]
Closing this pull request as repo structure has been altered

**Comment by avdg** [comment]
@skapin I wonder how much advance/disadvance there is in setting mime type by using

```
type="image/x-icon"
```

This should be used with ico files only, png uses image/png, gif uses image/gif, etc...

**Comment by avdg** [comment]
Well, I guess I won't implement it till I feel forced to use the type attribute

**Comment by avdg** [comment]
~~Pull request is up: https://github.com/skapin/TPP-Updates/pull/23~~

**Pull request closed without merging**
